version: '3.6'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=vishwajeet
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=Hermes

    ports:
      - "5432:5432"
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql

  postgres2:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=vishwajeet
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=KeyStore-1

    ports:
      - "5431:5432"
    volumes:
      - ./key_Store.sql:/docker-entrypoint-initdb.d/key_Store.sql
