-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE key_store
(
    keyid integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    keyval integer,
    lastval integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    active boolean,
    CONSTRAINT key_store_pkey PRIMARY KEY (keyid)
);
INSERT INTO key_store (keyval, lastval, active) VALUES
(1,1,true ),(2,2,true ),(3,4,true ),(4,4,true );

COMMIT;